import { ThemeProvider } from '../providers/theme-provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import config from '../../public/zidocs.json';
import { Sidebar } from '@/components/side-bar';
import { cn } from '@/lib/utils';

import { ZidocsConfig, getAllMdx } from '@/lib/mdx';
import { NavBar } from '@/components/nav-bar';
import '@fortawesome/fontawesome-svg-core/styles.css';

import { config as fontAwesomeConfig } from '@fortawesome/fontawesome-svg-core';
import { RightSideBar } from '@/components/right-side-bar';

fontAwesomeConfig.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });
export const configTyped = config as ZidocsConfig;

export const metadata: Metadata = {
  title: configTyped.name,
  icons: {
    icon: [`/${configTyped.favicon}`],
  },
  description: 'Generated by zidocs',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getAllMdx();

  return (
    <html lang="en">
      <body className={cn(`${inter.className} scroll-pt-24`)}>
        {/* <span
          className="fixed inset-0"
          style={{
            backgroundImage: 'url(/starter-kit/images/lightbackground.png)',
            backgroundRepeat: 'no-repeat',
            backgroundPosition: 'top right',
            backgroundAttachment: 'fixed',
          }}
        ></span> */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar config={configTyped} data={data} />
          <div className="m-auto max-w-8xl">
            <Sidebar className="fixed w-[18rem] lg:pl-8" data={data} />
            <div className="flex justify-center gap-12 p-6 lg:pl-[20rem]">
              {children}
              <div className="hidden w-[19rem] flex-none pl-10 xl:flex">
                <RightSideBar data={data} />
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
