import { ThemeProvider } from '../providers/theme-provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import config from '../../public/starter-kit/zidocs.json';
import { Sidebar } from '@/components/side-bar';
import { cn } from '@/lib/utils';

import { getSideBarData } from '@/lib/mdx';
import { NavBar } from '@/components/nav-bar';
import { LeftSideBar } from '@/components/left-side-bar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: config.name,
  icons: {
    icon: [`/starter-kit/${config.favicon}`],
  },
  description: 'Generated by zidocs',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getSideBarData();

  return (
    <html className="scroll-pt-24" lang="en">
      <head>
        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/github-dark.min.css"
        ></link> */}
      </head>
      <body className={cn(`${inter.className}`)}>
        <span
          className="fixed inset-0"
          style={{
            backgroundImage: 'url(/starter-kit/images/lightbackground.png)',
            backgroundRepeat: 'no-repeat',
            backgroundPosition: 'top right',
            backgroundAttachment: 'fixed',
          }}
        ></span>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar config={config} data={data} />

          <div className="m-auto max-w-8xl">
            <Sidebar className="fixed w-[18rem] lg:pl-8" data={data} />
            <div className="flex justify-center gap-12 p-6  lg:pl-[20rem]">
              <div className="relative w-full max-w-3xl grow overflow-hidden xl:max-w-[49rem] xl:pl-14">
                {children}
              </div>
              <div className="hidden w-[19rem] flex-none pl-10 xl:flex">
                <LeftSideBar data={data} />
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
